Default: &defaults
  database: thetask.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: thetask_test.sqlite3
  <<: *defaults

Staging:
  database: thetask_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: thetask_production.sqlite3
  poolsize: 100
  <<: *defaults
